# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171227_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='recv_data',
            new_name='recv_date',
        ),
    ]
