# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171227_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('weight', models.IntegerField(verbose_name='权重')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='customerdistribution',
            name='ctime',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdistribution',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealers', to='app01.Customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='customerdistribution',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='更多信息'),
        ),
        migrations.AddField(
            model_name='customerdistribution',
            name='status',
            field=models.IntegerField(choices=[(1, '正在跟进'), (2, '已成单'), (3, '三天未跟进'), (4, '十五天未成单')], default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='customerdistribution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cds', to='app01.UserInfo', verbose_name='当前客户顾问'),
        ),
    ]
