# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180102_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='openid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微信唯一ID'),
        ),
    ]
